/******************************************************************************/
//
// This file was generated by OSAcfg_Tool utility.
// Do not modify it to prevent data loss on next editing.
//
// PROJECT NAME:
//
// PLATFORM:     Microchip C18
//
/******************************************************************************/


#ifndef _OSACFG_H
#define _OSACFG_H

//------------------------------------------------------------------------------
// SYSTEM
//------------------------------------------------------------------------------

#define OS_TASKS                3  // Number of tasks that can be active at one time

#define OS_MSG_TYPE                 int
//------------------------------------------------------------------------------
// ENABLE CONSTANTS
//------------------------------------------------------------------------------

#define OS_ENABLE_ALL               // Enable all services: CSems, QMsg, QSmsg, TTimers, DTimers

#define OS_ENABLE_TTIMERS

//------------------------------------------------------------------------------
// BSEMS
//------------------------------------------------------------------------------

#define OS_BSEMS                1   // Number of binary semaphores
enum OSA_BSEMS_ENUM
{
   BS_ARE_FREE
};

#endif